################################################################################
# This is the template for appveyor.yml which uses the "default model" of the
# test framework in https://github.com/PowerShell/DscResource.Tests.
#
# This template assumes you have connected your repository to AppVeyor
# (https://ci.appveyor.com).
#
# Before using it in your repository, modify places marked with 'TODO:', and
# then remove this comment block.
################################################################################

#---------------------------------#
#      environment configuration  #
#---------------------------------#

version: 1.0.{build}.0 # TODO: Modify version so it fits your versioning.
environment:
  gallery_api:
    # TODO: Change to the correct API key if using PowerShell Gallery deploy task.
    # If you wish to use this to publish your own module you'd need to set your
    # own API key (encrypted by https://ci.appveyor.com/tools/encrypt).
    #
    # This API key can only be decrypted by the PowerShell Team's AppVeyor account,
    # and can only be used for resource modules under the DSC Resource Kit.
    secure: 9ekJzfsPCDBkyLrfmov83XbbhZ6E2N3z+B/Io8NbDetbHc6hWS19zsDmy7t0Vvxv

install:
    - git clone https://github.com/PowerShell/DscResource.Tests
    - ps: Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
    - ps: Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
    - ps: Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        # TODO:
        # To use -CodeCovIo parameter, the repository need to connected
        # to Codecov (see https://codecov.io/).
        Invoke-AppveyorTestScriptTask -CodeCoverage -CodeCovIo

# scripts to run before deployment
after_test:
    - ps: |
        Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorAfterTestTask

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy_script:
  - ps: |
        Invoke-AppVeyorDeployTask
